# Generated by Django 4.1.1 on 2022-10-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotel_images_delete_hotelimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='images',
            field=models.ImageField(upload_to='images'),
        ),
    ]
